-- Row Training V39 · calendario editable, multiequipo, competiciones y resultados MAR
create table if not exists public.coach_team_access (
  coach_user_id uuid not null references auth.users(id) on delete cascade,
  team_code text not null check (team_code in ('veteranas','senior_m','senior_f','veteranos_m')),
  primary key(coach_user_id,team_code)
);
create table if not exists public.training_sessions (
  id bigint generated by default as identity primary key,
  team_code text not null check (team_code in ('veteranas','senior_m','senior_f','veteranos_m')),
  session_date date not null,
  session_type text not null check (session_type in ('GYM','ERG','MAR','DESC')),
  title text not null,
  content text,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.competitions (
  id bigint generated by default as identity primary key,
  name text not null, competition_date date not null,
  team_codes text[] not null default '{}', priority text, notes text,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create table if not exists public.sea_results (
  id bigint generated by default as identity primary key,
  training_session_id bigint not null references public.training_sessions(id) on delete cascade,
  distance_m integer, time_text text, pace_500_text text, spm integer,
  rpe integer check (rpe between 1 and 10), notes text,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.coach_team_access enable row level security;
alter table public.training_sessions enable row level security;
alter table public.competitions enable row level security;
alter table public.sea_results enable row level security;

grant select,insert,update,delete on public.coach_team_access,public.training_sessions,public.competitions,public.sea_results to authenticated;
grant usage,select on sequence public.training_sessions_id_seq,public.competitions_id_seq,public.sea_results_id_seq to authenticated;

create or replace function public.can_manage_team(p_team text) returns boolean language sql stable security definer set search_path=public as $$
 select public.is_coach() and (
   not exists(select 1 from public.coach_team_access a where a.coach_user_id=auth.uid())
   or exists(select 1 from public.coach_team_access a where a.coach_user_id=auth.uid() and a.team_code=p_team)
 );
$$;

drop policy if exists coach_access_self_read on public.coach_team_access;
create policy coach_access_self_read on public.coach_team_access for select to authenticated using (coach_user_id=auth.uid() or public.is_coach());
drop policy if exists coach_access_coach_write on public.coach_team_access;
create policy coach_access_coach_write on public.coach_team_access for all to authenticated using (public.is_coach()) with check (public.is_coach());

drop policy if exists training_sessions_read on public.training_sessions;
create policy training_sessions_read on public.training_sessions for select to authenticated using (public.is_coach() or session_type<>'MAR');
drop policy if exists training_sessions_coach_write on public.training_sessions;
create policy training_sessions_coach_write on public.training_sessions for all to authenticated using (public.can_manage_team(team_code)) with check (public.can_manage_team(team_code));

drop policy if exists competitions_read on public.competitions;
create policy competitions_read on public.competitions for select to authenticated using (true);
drop policy if exists competitions_coach_write on public.competitions;
create policy competitions_coach_write on public.competitions for all to authenticated using (public.is_coach()) with check (public.is_coach());

drop policy if exists sea_results_coach_only on public.sea_results;
create policy sea_results_coach_only on public.sea_results for all to authenticated using (public.is_coach()) with check (public.is_coach());
