-- Row Training V40 · bibliotecas, bloques MAR, historial protegido y temporada 2026-27
-- Ejecutar DESPUÉS de setup_v39.sql

create table if not exists public.exercise_library (
 id bigint generated by default as identity primary key,
 category text not null check(category in ('GYM','ERG','MAR')),
 name text not null,
 description text, default_dose text, default_rest text,
 alternatives jsonb not null default '[]'::jsonb,
 image_key text, created_by uuid default auth.uid() references auth.users(id) on delete set null,
 is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(category,name)
);
create table if not exists public.session_blocks (
 id bigint generated by default as identity primary key,
 training_session_id bigint not null references public.training_sessions(id) on delete cascade,
 block_order integer not null default 1,
 library_exercise_id bigint references public.exercise_library(id) on delete set null,
 name text not null, mode text check(mode in ('TIEMPO','METROS','REPETICIONES','LIBRE')) default 'LIBRE',
 amount numeric, unit text, ppm numeric, level text check(level in ('BAJO','MEDIO','ALTO') or level is null),
 recovery text, cue text, created_at timestamptz not null default now()
);
create table if not exists public.session_history (
 id bigint generated by default as identity primary key,
 training_session_id bigint, team_code text not null, session_date date not null, session_type text not null,
 title text not null, snapshot jsonb not null, completed_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now()
);

alter table public.exercise_library enable row level security;
alter table public.session_blocks enable row level security;
alter table public.session_history enable row level security;
grant select,insert,update,delete on public.exercise_library,public.session_blocks,public.session_history to authenticated;
grant usage,select on sequence public.exercise_library_id_seq,public.session_blocks_id_seq,public.session_history_id_seq to authenticated;

drop policy if exists exercise_library_read on public.exercise_library;
create policy exercise_library_read on public.exercise_library for select to authenticated using(is_active or public.is_coach());
drop policy if exists exercise_library_write on public.exercise_library;
create policy exercise_library_write on public.exercise_library for all to authenticated using(public.is_coach()) with check(public.is_coach());
drop policy if exists session_blocks_read on public.session_blocks;
create policy session_blocks_read on public.session_blocks for select to authenticated using(
 exists(select 1 from public.training_sessions s where s.id=training_session_id and (public.is_coach() or s.session_type<>'MAR'))
);
drop policy if exists session_blocks_write on public.session_blocks;
create policy session_blocks_write on public.session_blocks for all to authenticated using(
 exists(select 1 from public.training_sessions s where s.id=training_session_id and public.can_manage_team(s.team_code))
) with check(exists(select 1 from public.training_sessions s where s.id=training_session_id and public.can_manage_team(s.team_code)));
drop policy if exists session_history_read on public.session_history;
create policy session_history_read on public.session_history for select to authenticated using(public.is_coach() or completed_by=auth.uid());
drop policy if exists session_history_write on public.session_history;
create policy session_history_write on public.session_history for insert to authenticated with check(public.is_coach() or completed_by=auth.uid());

-- Biblioteca GYM compacta + alternativas
insert into public.exercise_library(category,name,description,default_dose,default_rest,alternatives,image_key) values
('GYM','Sentadilla','Patrón principal de fuerza de piernas.','3×6-10','2 min','["Sentadilla goblet a cajón","Prensa","Zancada asistida"]','goblet'),
('GYM','Remo tumbado / pecho apoyado','Tracción principal con tronco estable.','3×8-12','90 s','["Remo con mancuerna","Remo con banda","Jalón al pecho"]','remo'),
('GYM','Prensa','Fuerza de piernas con ejecución sencilla.','3×8-10','2 min','["Sentadilla goblet","Zancada asistida"]','prensa'),
('GYM','Peso muerto rumano','Cadena posterior y control de cadera.','3×6-10','2 min','["RDL con mancuernas","Buenos días con banda","Hip thrust"]','rumano'),
('GYM','Hip thrust / puente','Extensión de cadera.','3×8-12','90 s','["Puente a una pierna","Hip thrust con mancuerna"]','hip'),
('GYM','Press','Empuje para equilibrio estructural.','3×8-12','90 s','["Press con mancuernas","Flexiones"]','press'),
('GYM','Pallof press','Core antirotación.','3×10-12/lado','60 s','["Plancha","Dead bug"]','pallof'),
('GYM','Plancha','Estabilidad de tronco.','3×30-45 s','60 s','["Pallof press","Dead bug"]','plancha')
on conflict(category,name) do nothing;

-- Biblioteca MAR: una única denominación Virada-Ciaboga. La embarcación la decide el entrenador fuera de la prescripción.
insert into public.exercise_library(category,name,description,default_dose,default_rest,alternatives) values
('MAR','Técnica a baja frecuencia','Secuencia técnica, salida de brazos, conexión de core y longitud de palada.','10-20 min','Según objetivo','[]'),
('MAR','Salidas','Practicar la salida propia de la tripulación.','4-8 repeticiones','Recuperación completa','[]'),
('MAR','Salida + aceleración','Salida propia + transición progresiva al ritmo indicado.','4-6 repeticiones','2-4 min','[]'),
('MAR','Virada-Ciaboga','Entrada, ejecución y salida de la maniobra.','6-10 repeticiones','1-3 min','[]'),
('MAR','Virada-Ciaboga + aceleración','Maniobra seguida de aceleración controlada.','4-6 repeticiones','2-3 min','[]'),
('MAR','Series por metros','Bloques configurables por distancia, ppm y recuperación.','Configurable','Configurable','[]'),
('MAR','Series por tiempo','Bloques configurables por tiempo, ppm y recuperación.','Configurable','Configurable','[]'),
('MAR','Pirámide de ritmos','Cambios de ppm continuos o con recuperación.','Configurable','Configurable','[]')
on conflict(category,name) do nothing;

-- ERGO: catálogo base. Enlaces ErgData se siguen gestionando en ergo_library.
insert into public.exercise_library(category,name,description,default_dose,default_rest,alternatives) values
('ERG','UT2 continuo/fraccionado','Base aeróbica técnica.','2-4 bloques de 8-12 min','3 min','[]'),
('ERG','UT1 por metros','Trabajo aeróbico medio.','500-2000 m por serie','2-4 min','[]'),
('ERG','UT1-AT progresivo','Cambios de ritmo controlados.','Bloques progresivos','3-5 min','[]'),
('ERG','AT','Trabajo de umbral.','3-6 repeticiones','3 min','[]'),
('ERG','TR-AN','Series cortas de alta intensidad.','Según fase','Completa','[]'),
('ERG','CONTROL','Control específico; 1000 m Veteranas / 2000 m Senior masculino.','1 test','-','[]')
on conflict(category,name) do nothing;

-- Temporada base 2026-27 para los dos equipos ya planificados. Lunes-domingo real.
-- Se crean solo fechas futuras sin sesión existente; el entrenador puede editar todo desde el panel.
do $$
declare d date; wk int; phase text; team text; gymtitle text; ergotitle text; martitle text;
begin
 for team in select unnest(array['veteranas','senior_m']) loop
  d := date '2026-09-01';
  while d <= date '2027-05-31' loop
   wk := floor((d-date '2026-09-01')/7)+1;
   phase := case when d < '2026-11-01' then 'BASE' when d < '2027-01-01' then 'FUERZA' when d < '2027-03-01' then 'TRANSFERENCIA' when d < '2027-04-15' then 'ESPECIFICO' else 'PUESTA A PUNTO' end;
   -- Martes GYM
   if extract(isodow from d)=2 and not exists(select 1 from public.training_sessions s where s.team_code=team and s.session_date=d and s.session_type='GYM') then
    gymtitle := case phase when 'BASE' then 'GYM · Fuerza general' when 'FUERZA' then 'GYM · Fuerza máxima controlada' when 'TRANSFERENCIA' then 'GYM · Fuerza + transferencia' when 'ESPECIFICO' then 'GYM · Mantenimiento de fuerza' else 'GYM · Activación / mantenimiento' end;
    insert into public.training_sessions(team_code,session_date,session_type,title,content) values(team,d,'GYM',gymtitle,'Catálogo principal: sentadilla/prensa · RDL/hip thrust · remo · press · core. Sin llegar al fallo; ajustar volumen según competición y fatiga.');
   end if;
   -- Viernes segundo GYM; Senior puede usar miércoles como tercer día en base/fuerza
   if extract(isodow from d)=5 and not exists(select 1 from public.training_sessions s where s.team_code=team and s.session_date=d and s.session_type='GYM') then
    insert into public.training_sessions(team_code,session_date,session_type,title,content) values(team,d,'GYM','GYM · Fuerza específica','5-6 ejercicios del catálogo. Prioridad piernas/cadena posterior/espalda/core. Reducir volumen en semana de competición.');
   end if;
   if team='senior_m' and d<'2027-02-01' and extract(isodow from d)=3 and not exists(select 1 from public.training_sessions s where s.team_code=team and s.session_date=d and s.session_type='GYM') then
    insert into public.training_sessions(team_code,session_date,session_type,title,content) values(team,d,'GYM','GYM · Complementario','Sesión breve de fuerza/estabilidad sin interferir con el MAR del jueves.');
   end if;
   -- ERGO: Veteranas miércoles; Senior sábado. Progresión por fase.
   if ((team='veteranas' and extract(isodow from d)=3) or (team='senior_m' and extract(isodow from d)=6)) and not exists(select 1 from public.training_sessions s where s.team_code=team and s.session_date=d and s.session_type='ERG') then
    ergotitle := case phase when 'BASE' then 'ERGO · UT2' when 'FUERZA' then 'ERGO · UT1' when 'TRANSFERENCIA' then 'ERGO · UT1-AT' when 'ESPECIFICO' then 'ERGO · AT / calidad' else 'ERGO · Activación / control' end;
    insert into public.training_sessions(team_code,session_date,session_type,title,content) values(team,d,'ERG',ergotitle,'Seleccionar desde Biblioteca ERGO según semana y estado del equipo. Mantener volumen UT2/UT1 durante toda la temporada; introducir AT/TR-AN progresivamente.');
   end if;
   -- MAR jueves y domingo: técnica + salidas + Virada-Ciaboga + ritmo. PPM siempre editable por entrenador.
   if extract(isodow from d) in (4,7) and not exists(select 1 from public.training_sessions s where s.team_code=team and s.session_date=d and s.session_type='MAR') then
    martitle := case phase when 'BASE' then 'MAR · Técnica y base' when 'FUERZA' then 'MAR · Técnica + fuerza por palada' when 'TRANSFERENCIA' then 'MAR · Ritmo + maniobras' when 'ESPECIFICO' then 'MAR · Específico de competición' else 'MAR · Calidad y puesta a punto' end;
    insert into public.training_sessions(team_code,session_date,session_type,title,content) values(team,d,'MAR',martitle,
      case phase
       when 'BASE' then 'Calentamiento · técnica a baja frecuencia · salidas controladas · Virada-Ciaboga · bloque aeróbico · vuelta a la calma. PPM a decisión del entrenador.'
       when 'FUERZA' then 'Calentamiento · técnica · salidas · Virada-Ciaboga · bloques de fuerza por palada/ritmo medio · vuelta a la calma.'
       when 'TRANSFERENCIA' then 'Calentamiento · salidas + aceleración · Virada-Ciaboga · series por tiempo o metros · pirámides de ritmo · vuelta a la calma.'
       when 'ESPECIFICO' then 'Calentamiento · salidas específicas · Virada-Ciaboga a intensidad · series específicas por tiempo/metros · recuperación completa · vuelta a la calma.'
       else 'Volumen reducido · técnica limpia · salidas · Virada-Ciaboga · esfuerzos cortos de calidad. Evitar fatiga residual.' end);
   end if;
   d := d + 1;
  end loop;
 end loop;
end $$;
