-- Row Training V36 · Concept2 persistence and matching
-- Run once in Supabase > SQL Editor.

create table if not exists public.concept2_connections (
  user_id uuid primary key references auth.users(id) on delete cascade,
  concept2_user_id text,
  concept2_username text,
  access_token text not null,
  refresh_token text not null,
  expires_at timestamptz not null,
  scope text not null default 'user:read,results:read',
  last_sync_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- IMPORTANT: OAuth tokens are server-only. No browser policy is created.
alter table public.concept2_connections enable row level security;
revoke all on public.concept2_connections from anon, authenticated;

create table if not exists public.ergo_intents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  scheduled_date date not null,
  session_code text not null,
  session_name text,
  expected_distance_m integer,
  expected_workout_type text,
  ergdata_url text,
  created_at timestamptz not null default now()
);
alter table public.ergo_intents enable row level security;
grant select,insert,update,delete on public.ergo_intents to authenticated;
grant usage,select on sequence public.ergo_intents_id_seq to authenticated;

drop policy if exists "ergo_intents_own" on public.ergo_intents;
create policy "ergo_intents_own" on public.ergo_intents
for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);

create table if not exists public.concept2_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  concept2_result_id text not null,
  workout_date timestamptz,
  distance_m integer,
  time_tenths integer,
  time_formatted text,
  pace_500_seconds numeric,
  spm integer,
  avg_hr integer,
  max_hr integer,
  workout_type text,
  source text,
  matched_intent_id bigint references public.ergo_intents(id) on delete set null,
  matched_session_code text,
  match_status text not null default 'unplanned' check (match_status in ('matched','review','unplanned')),
  match_confidence integer not null default 0,
  raw_result jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,concept2_result_id)
);
alter table public.concept2_results enable row level security;
grant select on public.concept2_results to authenticated;
grant usage,select on sequence public.concept2_results_id_seq to authenticated;

drop policy if exists "concept2_results_own_read" on public.concept2_results;
create policy "concept2_results_own_read" on public.concept2_results
for select to authenticated using (auth.uid()=user_id);

drop policy if exists "concept2_results_coach_read" on public.concept2_results;
create policy "concept2_results_coach_read" on public.concept2_results
for select to authenticated using (public.is_coach());
