-- Row Training V43: biblioteca editable GYM/MAR
create table if not exists public.training_library (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('GYM','MAR')),
  name text not null,
  content text,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.training_library enable row level security;

drop policy if exists training_library_read on public.training_library;
create policy training_library_read on public.training_library
for select to authenticated using (true);

drop policy if exists training_library_coach_insert on public.training_library;
create policy training_library_coach_insert on public.training_library
for insert to authenticated with check (public.is_coach());

drop policy if exists training_library_coach_update on public.training_library;
create policy training_library_coach_update on public.training_library
for update to authenticated using (public.is_coach()) with check (public.is_coach());

drop policy if exists training_library_coach_delete on public.training_library;
create policy training_library_coach_delete on public.training_library
for delete to authenticated using (public.is_coach());

insert into public.training_library(kind,name,content)
select * from (values
 ('GYM','Fuerza general · catálogo corto','Sentadilla/prensa · RDL/hip thrust · remo · press · core. Ajustar series, repeticiones y carga según fase y proximidad de competición.'),
 ('MAR','Técnica + Virada-Ciaboga','Técnica a baja frecuencia · Virada-Ciaboga · salidas propias del equipo · recuperación completa entre repeticiones.'),
 ('MAR','Pirámide de ritmos','Pirámide continua o por bloques. Ejemplo: 20-22-24-26-28 ppm. Duración/metraje y recuperación editables.'),
 ('MAR','Salidas','Repeticiones de la salida propia del equipo. Número de repeticiones, metros y recuperación a elección del entrenador.')
) as v(kind,name,content)
where not exists (select 1 from public.training_library t where t.kind=v.kind and t.name=v.name);
